### PR TITLE
migrate the canbus, controldev and sonar_tritech to "modern syskit"

### PR DESCRIPTION
**Pull request by doudou**
@gustavoneves12: you could have a look at this ... some parts are a bit advanced (the com_bus stuff), but some parts are very straightforward and "clean". Could give you ideas / raise questions.

### CODE REVIEW

**Comment by gustavoneves12** [comment]
I will analyse it, but I guess that this will generate a lot of question.

**Comment by doudou** [comment]
> but I guess that this will generate a lot of question.

This is why I point it to you, that you can ask questions ;-)

**Comment by gustavoneves12** [comment]
How can I test it?
I am going to use "rake test" to check if everything is ok.

**Comment by doudou** [comment]
Won't work

In principle, you should run

```
bundle-sel .
syskit test
```

However, there is a problem with this bundle: it's integrating a lot of stuff, which means that you currently can run the tests only if you have all the Rock packages installed (not very practical).

In our case, you can comment out the trajectory_follower_control_loop in test/suite_compositions and the tests should pass.

**Comment by gustavoneves12** [comment]
@doudou, I executed the syskit test and I got 3 errors, even with the trajectory_follower_control_loop commented. Can I merge even with these errors? Below you have the backtrace.

```
17:31:16.385 (Roby) debugging is disabled because the 'pry' gem cannot be loaded
Bundles[INFO]: Active bundles: rock
Syskit[WARN]: debugging is disabled because the 'pry' gem cannot be loaded
17:31:17.682 (Roby) skipping /home/gustavoneves/rock-robotics/bundles/rock/test/orogen/test_gps.rb: there is no project named gps on #<Orocos::DefaultLoader(19cfe90): #<OroGen::Loaders::PkgConfig(1b984ac) gnulinux>,#<OroGen::Loaders::Files(1f46284) projects= typekits=>,#<Orocos::ROS::DefaultLoader packs=[] search_path=["/home/gustavoneves/rock-robotics/tools/orogen/lib/orogen/ros"]>,#<OroGen::Loaders::Files(1f64734) projects= typekits=>,#<OroGen::ROS::Loader packs=[] search_path=[]>>
17:31:17.707 (Roby) skipping /home/gustavoneves/rock-robotics/bundles/rock/test/orogen/test_envire.rb: there is no project named envire on #<Orocos::DefaultLoader(19cfe90): #<OroGen::Loaders::PkgConfig(1b984ac) gnulinux>,#<OroGen::Loaders::Files(1f46284) projects= typekits=>,#<Orocos::ROS::DefaultLoader packs=[] search_path=["/home/gustavoneves/rock-robotics/tools/orogen/lib/orogen/ros"]>,#<OroGen::Loaders::Files(1f64734) projects= typekits=>,#<OroGen::ROS::Loader packs=[] search_path=[]>>
Syskit[WARN]: it_should_be_configurable is deprecated, use
Syskit[WARN]:   it { is_configurable } instead
Syskit[WARN]: it_should_be_configurable is deprecated, use
Syskit[WARN]:   it { is_configurable } instead
Run options: -v --seed 11374

# Running:

0.881 [ ERROR  ][Logger] orogen_typekits::toCORBA() invalid value '74587392' for enum '::canbus::DRIVER_TYPE'
OroGen::Canbus::Task#test_0002_calls the watch operation for each attached device = 0.08 s = S
0.886 [ ERROR  ][Logger] orogen_typekits::toCORBA() invalid value '65323520' for enum '::canbus::DRIVER_TYPE'
OroGen::Canbus::Task#test_0001_fails on configure if a device has no can ID = 0.00 s = S
Rock::Compositions::ControlLoop::closed loop::the forwarding specialization#test_0002_connects the command ports = 0.15 s = .
Rock::Compositions::ControlLoop::closed loop::the forwarding specialization#test_0001_connects the status ports = 0.18 s = .
Rock::Compositions::ControlLoop::open loop::the forwarding specialization#test_0001_connects the command ports = 0.12 s = .
Rock::Compositions::ControlLoop::closed loop::the cascading specialization#test_0001_provides the controlled system service = 0.14 s = .
Rock::Compositions::ControlLoop::closed loop::the cascading specialization#test_0003_exports the command in port = 0.14 s = .
Rock::Compositions::ControlLoop::closed loop::the cascading specialization#test_0002_exports the status_out port = 0.17 s = .
Rock::Services::ControlLoop::closed-loop control::controller_for#test_0001_returns the generated controller model = 0.11 s = .
Rock::Compositions::ConstantGenerator#test_0001_validates that the keys in 'values' are actual port names = 0.11 s = .
Rock::Compositions::ControlLoop::open loop::the cascading specialization#test_0001_provides the controlled system service = 0.12 s = .
Rock::Compositions::ControlLoop::open loop::the cascading specialization#test_0002_exports the command in port = 0.13 s = .
OroGen::RockGazebo::ModelTask#test_0001_anonymous = 0.47 s = .
OroGen::Taskmon::Task#test_0001_anonymous = 0.28 s = .
OroGen::Taskmon::Task#test_0002_calls add_watches with the PID of the new deployments = 0.38 s = .
OroGen::Taskmon::Task#test_0003_calls add_watches with the new orocos tasks = 0.43 s = .
Rock::Devices::Bus::CAN#test_0002_raises ArgumentError if the can ID and mask do not make sense = 0.10 s = E
Rock::Devices::Bus::CAN#test_0001_allows to specify the can ID on the attached devices = 0.10 s = E
Rock::Compositions::ConstantGenerator::defined from a data service#test_0001_constantly writes data to its output port = 0.46 s = .
Rock::Compositions::ConstantGenerator::defined from a data service#test_0002_returns the same component over and over again = 0.11 s = .
OroGen::RockGazebo::WorldTask#test_0001_anonymous = 0.28 s = .
OroGen::IodriversBase::Task#test_0001_anonymous = 0.13 s = E
OroGen::IodriversBase::Proxy#test_0001_anonymous = 0.31 s = .
Rock::Services::ControlLoop::closed-loop control#test_0004_creates ports that allow for a feedback = 0.11 s = .
Rock::Services::ControlLoop::closed-loop control#test_0003_leaves the open-loop models untouched = 0.11 s = .
Rock::Services::ControlLoop::closed-loop control#test_0002_sets up the relationship between the open and closed loop models = 0.11 s = .
Rock::Services::ControlLoop::closed-loop control#test_0001_sets up the relationship between the closed loop models and the root models = 0.11 s = .
Rock::Services::ControlLoop#test_0001_raises if the services are already declared = 0.11 s = .
Rock::Services::ControlLoop::closed-loop control::controlled_system_for#test_0001_returns the generated controlled system model = 0.11 s = .
Rock::Services::ControlLoop::open-loop control#test_0001_properly sets up the relationship between the open loop models and the root models = 0.11 s = .
Rock::Services::ControlLoop::open-loop control#test_0002_creates ports that allow for an open-loop connection = 0.11 s = .
Transformer[WARN]: no frame selected for world on tProxy(OroGen::TrajectoryFollower::Task:0x3db1408){trajectory => default(nil), conf => default([default])}. This is harmless for the network to run, but will make the display of trajectory "in the right frame" impossible
OroGen::TrajectoryFollower::Task#test_0001_should be configurable = 0.35 s = .
Transformer[WARN]: no frame selected for world on tProxy(OroGen::TrajectoryFollower::Task:0x42239a0){trajectory => [#</base/Trajectory_m: 0x42191f8 ptr=0x5a7c180>], conf => default([default])}. This is harmless for the network to run, but will make the display of trajectory "in the right frame" impossible
OroGen::TrajectoryFollower::Task#test_0002_should pass non-nil trajectory argument to the task = 0.53 s = .

Finished in 6.325360s, 5.2171 runs/s, 4.7428 assertions/s.

  1) Skipped:
OroGen::Canbus::Task#test_0002_calls the watch operation for each attached device [/home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/test/task_context_test.rb:73]:
OroGen::Canbus::Task#test_0002_calls the watch operation for each attached device cannot run: failed to marshal /canbus/DRIVER_TYPE


  2) Skipped:
OroGen::Canbus::Task#test_0001_fails on configure if a device has no can ID [/home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/test/task_context_test.rb:73]:
OroGen::Canbus::Task#test_0001_fails on configure if a device has no can ID cannot run: failed to marshal /canbus/DRIVER_TYPE


  3) Error:
Rock::Devices::Bus::CAN#test_0002_raises ArgumentError if the can ID and mask do not make sense:
/home/gustavoneves/rock-robotics/bundles/rock/test/devices/bus/test_can.rb:14:in `block (2 levels) in <module:Bus>': undefined method `syskit_stub_attached_device' for #<#<Class:0x000000033bc6c8>:0x00000003c3c8c0> (NoMethodError)
    /home/gustavoneves/rock-robotics/bundles/rock/test/devices/bus/test_can.rb:14:in `block (2 levels) in <module:Bus>'
    /home/gustavoneves/rock-robotics/tools/roby/lib/roby/test/spec.rb:41:in `instance_eval'
    /home/gustavoneves/rock-robotics/tools/roby/lib/roby/test/spec.rb:41:in `block in it'


  4) Error:
Rock::Devices::Bus::CAN#test_0001_allows to specify the can ID on the attached devices:
/home/gustavoneves/rock-robotics/bundles/rock/test/devices/bus/test_can.rb:8:in `block (2 levels) in <module:Bus>': undefined method `syskit_stub_attached_device' for #<#<Class:0x000000033bc6c8>:0x00000003c79e28> (NoMethodError)
    /home/gustavoneves/rock-robotics/bundles/rock/test/devices/bus/test_can.rb:8:in `block (2 levels) in <module:Bus>'
    /home/gustavoneves/rock-robotics/tools/roby/lib/roby/test/spec.rb:41:in `instance_eval'
    /home/gustavoneves/rock-robotics/tools/roby/lib/roby/test/spec.rb:41:in `block in it'


  5) Error:
OroGen::IodriversBase::Task#test_0001_anonymous:
/home/gustavoneves/rock-robotics/tools/orogen/lib/orogen/loaders/aggregate.rb:173:in `deployment_model_from_name': there is no deployment named orogen_default_iodrivers_base__Task on #<Orocos::DefaultLoader(19cfe90): #<OroGen::Loaders::PkgConfig(1b984ac) gnulinux>,#<OroGen::Loaders::Files(1f46284) projects= typekits=>,#<Orocos::ROS::DefaultLoader packs=[] search_path=["/home/gustavoneves/rock-robotics/tools/orogen/lib/orogen/ros"]>,#<OroGen::Loaders::Files(1f64734) projects= typekits=>,#<OroGen::ROS::Loader packs=[] search_path=[]>> (OroGen::DeploymentModelNotFound)
    /home/gustavoneves/rock-robotics/tools/orogen/lib/orogen/loaders/aggregate.rb:173:in `deployment_model_from_name'
    /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/roby_app/plugin.rb:389:in `using_deployment'
    /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/roby_app/configuration.rb:389:in `block in use_deployment'
    /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/roby_app/configuration.rb:387:in `map'
    /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/roby_app/configuration.rb:387:in `use_deployment'
    /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/test/network_manipulation.rb:28:in `use_deployment'
    /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/test/task_context_test.rb:14:in `deploy_subject_syskit_model'
    /home/gustavoneves/rock-robotics/tools/syskit/lib/syskit/test/task_context_test.rb:8:in `setup'

33 runs, 30 assertions, 0 failures, 3 errors, 2 skips
```

**Comment by doudou** [comment]
OK ... there were a bunch of issues with the tests. Limitations on the syskit side that caused these issues. I'm merging this and opened issue #2 to keep in mind that we should check again that it passes once all pending PRs are merged on orogen, syskit and roby

**Pull request merged**
